### ISSUE TITLE
generate_headers.py: Handle case where device has no interrupts

### ISSUE THREAD

**Issue by richardxia** [sifive/api-generator-sifive#32]
Currently, if you try to run the header generation flow on a design where the device has no interrupts, the `generate_header.py` script blows up on this line because you can't call `min()` on an empty collection:

https://github.com/sifive/api-generator-sifive/blob/18c8cb15cc765e49f5ec03607aafc45a32ddac11/scripts/generate_header.py#L412

We should fix this so that the script handles the case where a device doesn't have interrupts.

**Comment by sistillson** [comment]
see https://github.com/sifive/api-generator-sifive/pull/34
